gafc/urls.py
# -*- coding: utf-8 -*-
#
# This file is part of GAFC.
#
# GAFC is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# GAFC is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with GAFC. If not, see <https://www.gnu.org/licenses/>. 
#
# 2022 - William Chèvremont

"""
GAFC main URL router
"""

from django.urls import path, re_path, register_converter
from django.views.decorators.csrf import csrf_exempt
from .views import callback, categories, equipments, events, financials, home, logins, persons, settings, dashboard, jsondata, permissions, mailings
from datetime import datetime


class DateConverter:
    """
    Custom converter for dates in url
    """
    regex = '\d{4}-\d{2}-\d{2}'

    def to_python(self, value):
        """
        Convert the date to python date
        :param value: Date in Y-m-d format
        :type value: str
        :return date
        :rtype datetime.datetime
        """
        return datetime.strptime(value, '%Y-%m-%d')

    def to_url(self, value):
        """
        Convert the date to string
        :param value: Date
        :type value: datetime.datetime or datetime.date
        :return date
        :rtype str
        """
        return value.strftime('%Y-%m-%d')
    
register_converter(DateConverter, 'dateYmd')


urlpatterns = [
    # Home
    path('', home.HomeView.as_view() , name='home'),
    path('season/set', home.SetSeasonView.as_view(), name='set_season'),
    
    # Dashboard
    path('dashboard', dashboard.DashboardView.as_view(), name='dashboard'),
    path('dashboard/<dateYmd:today>', dashboard.DashboardView.as_view(), name='dashboard'),
    
    path('dashboard/plot/members_ages', dashboard.DashboardGraphsView.as_view(action='members_by_age'), name="dashboard_members_ages"),
    path('dashboard/plot/members_ages/<dateYmd:today>', dashboard.DashboardGraphsView.as_view(action='members_by_age'), name="dashboard_members_ages"),
    
    path('dashboard/plot/members_timeline', dashboard.DashboardGraphsView.as_view(action='adhesions_timeline'), name="dashboard_adhesions_timeline"),
    path('dashboard/plot/members_timeline/<dateYmd:today>', dashboard.DashboardGraphsView.as_view(action='adhesions_timeline'), name="dashboard_adhesions_timeline"),
    
    path('dashboard/plot/members_firstyear', dashboard.DashboardGraphsView.as_view(action='members_by_firstyear'), name="dashboard_members_firstyear"),
    path('dashboard/plot/members_firstyear/<dateYmd:today>', dashboard.DashboardGraphsView.as_view(action='members_by_firstyear'), name="dashboard_members_firstyear"),
    
    path('dashboard/plot/mixity/<int:sid>', dashboard.MixityGraphsView.as_view(), name='mixityPlot'),
    path('dashboard/plot/mixity/<int:sid>/<int:catid>', dashboard.MixityGraphsView.as_view(), name='mixityPlot'),
    
    
    # Json data
    path('jsondata/persons', jsondata.JsonDataView.as_view(action='persons'), name="persons_json"),
    path('jsondata/events', jsondata.JsonDataView.as_view(action='events'), name="events_json"),
    path('jsondata/events/all', jsondata.JsonDataView.as_view(action='events'), {'allevt': True}, name="events_json_all"),
    path('jsondata/payments', jsondata.JsonDataView.as_view(action='payments'), name="payments_json"),
    
    # Events
    path('event/calendar', events.EventsView.as_view(), name='list_events'),
    path('event/calendar/<int:year>/<int:month>', events.EventsView.as_view(), name='list_events'),
    path('event/<int:event_id>',events.EventView.as_view(), name='event'), 
    path('event/<int:event_id>/licenses', events.EventLicenseView.as_view(), name='event_licenses'),
    path('event/participation/<int:event_id>', events.EventParticipationView.as_view(), name='event_participation'),
    path('event/<int:eid>/export',events.EventExportView.as_view(), name='event_export'),   
    
    path('events/calendar/<int:cid>', events.EventICSCalendarView.as_view()),
    
    # Login Logout, Register, ...
    path('login', logins.LoginView.as_view(), name='login'),
    path('logout', logins.LogoutView.as_view(), name='logout'),
    path('register', logins.RegisterView.as_view(), name='new_account'),
    path('lost_password', logins.LostPasswordRequestView.as_view(), name="lost_password"),
    path('new_lost_password/<int:id>/<str:token>', logins.NewPasswordProcessView.as_view(), name="new_lost_password"),
    
    # Persons
    path('person/list', persons.PersonListView.as_view(), name='list_persons'),
    path('person/list/<int:page>',persons.PersonListView.as_view(), name='list_persons'),
    re_path(r'^person/list/(?P<name_first_letter>[a-zA-Z])$',persons.PersonListView.as_view(), name='list_persons'),
    re_path(r'^person/list/(?P<name_first_letter>[a-zA-Z])/(?P<page>[0-9]+)$',persons.PersonListView.as_view(), name='list_persons'),
    path('person/staffing',persons.PersonsStaffingView.as_view(), name='staffing_all'),
    path('person/<int:person_id>', persons.PersonView.as_view(), name='person'),
    path('person/var_person_id', persons.PersonView.as_view(), name='person_js'),
    #path('import_members/', persons.upload_from_memberlist, name='import_members'),
    #path('import_licenses/', persons.import_licenses, name='import_licenses'),
    
    # Mailing list
    path('mailing/', mailings.MailingListListView.as_view(), name='mailings'),
    path('mailing/<str:mlname>', mailings.MailingListView.as_view(), name='mailing'),
    
    # Permissions
    path('permissions/', permissions.PermissionsView.as_view(), name='permissions'),
    path('permissions/<int:group_id>', permissions.PermissionsGroupView.as_view() , name="permission_group"),
    
    # Categories
    path('category/<int:category_id>/events/export', categories.CategoryEventsCSVExportView.as_view(), name='category_events_export'),
    path('category/<int:category_id>/stats/participations', categories.CategoryParticipationGraphView.as_view() , name='category_p_repartition'),
    path('category/<int:category_id>', categories.CategoryView.as_view(), name='category'),
    path('category/<int:category_id>/events/edit', categories.CategoryEventsEdit.as_view(), name='category_events_edit'),
    path('category/<int:category_id>/events/edit/<int:year>/<int:month>', categories.CategoryEventsEdit.as_view(), name='category_events_edit'),
    
    # Cashing
    path('financials/cashing/list', financials.CashingListView.as_view(), name='financial'),
    path('financials/cashing/mylist', financials.CashingUserView.as_view(), name='financial_refund' ),
    path('financials/cashing/list/<int:year>', financials.CashingListView.as_view(), name='financial'),
    path('financials/cashing/<int:cid>', financials.CashingView.as_view(), name='cashing'),
    path('financials/cashing/file/<int:fid>', financials.CashingFileDownloadView.as_view(), name='cashing_file'),
    path('financials/cashing/signature/<int:fid>', financials.CashingSignatureFileDownloadView.as_view(), name='cashing_signature'),
    
    # Forseenbalance
    path('financials/forseenbalance/list', financials.ForseenBalanceListView.as_view(), name="fin_forseenbalances"),
    path('financials/forseenbalance/<int:balid>', financials.ForseenBalanceView.as_view(), name="fin_forseenbalance"),
    
    #Bank account operation
    path('financials/bankaccount/', financials.AccountOperationView.as_view(), name='accountoperations'),
    path('financials/bankaccount/balances', financials.AccountBalanceView.as_view(), name='accountbalance'),
    path('financials/bankaccount/<int:year>', financials.AccountOperationView.as_view(), name='accountoperations'),
    path('financials/bankaccount/processfile', financials.AccountOperationFileView.as_view(), name='accountoperations_file'),
    
    # Financial category manager
    path('financial/categories', financials.FinancialCategoryView.as_view(), name='fincat'),
    
    # Single operations
    path('financials/payment/<int:payment_id>', financials.PaymentView.as_view(), name='payment'),
    path('financials/transfer/<int:tid>', financials.TransferView.as_view(), name='transfer'),
    path('financials/operation/<int:opid>', financials.OperationView.as_view(), name='operation'),
    
    # Helloasso
    path('financials/payments/helloasso', financials.HelloassoPaymentView.as_view(), name='helloasso_payments'),
    
    # Balances
    path('financials/balance/daily', financials.BalanceView.as_view(action='balance_tmp'), name="fin_balance"),
    path('financials/balance/done', financials.BalanceView.as_view(action='balance_done'), name="fin_balance_done"),
    
    # Equipments
    path('equipment/list', equipments.EquipmentListView.as_view(), name='list_equipment'),
    path('equipment/<int:eqid>', equipments.EquipmentView.as_view(), name='equipment'),
    path('equipment/picture/<int:picture_id>', equipments.EquipmentPictureView.as_view() , name='equipment_picture'),
    path('equipment/calendar', equipments.EquipmentCalendarView.as_view(), name='calendar_equipment'),
    path('equipment/calendar/<int:year>/<int:month>', equipments.EquipmentCalendarView.as_view(), name='calendar_equipment'),
    path('equipment/group/<int:eqgrp_id>', equipments.EquipmentGroupView.as_view(), name='equipment_grp'),
    path('equipment/tracking/<int:tracking_id>', equipments.EquipmentTrackingView.as_view(), name='equipmenttracking'),
    
    # Settings
    path('settings', settings.SettingsView.as_view(), name='settings'),
    
    #Export
    path('export/season_archive/<int:sid>', settings.SeasonArchiveView.as_view(), name='season_archive'),

gucem/urls.py
# -*- coding: utf-8 -*-
#
# This file is part of GAFC.
#
# GAFC is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# GAFC is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with GAFC. If not, see <https://www.gnu.org/licenses/>. 
#
# 2022 - William Chèvremont

"""gucem URL Configuration
"""

from django.urls import include,path, re_path
from django.conf.urls import handler404, handler500, handler403
from .views import redirect_view
from django.conf import settings
from django.conf.urls.static import static

from gafc.views import handlers as gv
import gucem.settings as gset

urlpatterns = [
    path('',redirect_view),
    path('gafc/main/', include('gafc.urls'), name="intranet"),
    path('gafc/minibus/', include('vehicles.urls'), name="minibus"),
    path('gafc/formation/', include('formation.urls'), name='formation'),
    path('gafc/keys/', include('keys.urls'), name='keys'),
    re_path('gafc/[a-z]*$',redirect_view),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) # Only for development. Need static file server for production;

handler403 = gv.handler403
handler404 = gv.handler404
handler500 = gv.handler500

if gset.DEBUG:
    try:
        import debug_toolbar
        urlpatterns += [ path('__debug__/', include(debug_toolbar.urls)), ]
    except Exception as e:
        print(e)

vehicles/urls.py
# -*- coding: utf-8 -*-
#
# This file is part of GAFC.
#
# GAFC is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# GAFC is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with GAFC. If not, see <https://www.gnu.org/licenses/>. 
#
# 2022 - William Chèvremont 


from django.urls import path
from . import views

urlpatterns = [
    path('', views.CalcFeeView.as_view(), name='vehicle_home'),
    
    path('view', views.VehicleTableView.as_view(), name='vehicle_view'),
    path('view/<str:action>/<int:tid>', views.VehicleTableView.as_view(), name="vehicle_view_action"),
    path('view/<int:year>', views.VehicleTableView.as_view(), name="vehicle_view_year"),
    
    path('financial', views.VehicleFinancialView.as_view(), name="vehicle_financial"),
    path('settings', views.VehicleSettingView.as_view() , name="vehicle_settings"),
    path('statistics', views.VehicleStatisticView.as_view(), name="vehicle_statistics"),
]

vehicles/models.py
# -*- coding: utf-8 -*-
#
# This file is part of GAFC.
#
# GAFC is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# GAFC is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with GAFC. If not, see <https://www.gnu.org/licenses/>. 
#
# 2022 - William Chèvremont


from django.db import models
from gafc import models as gm
from django.utils import timezone

# Create your models here.

class Vehicle(models.Model):
    """
    This model represent a vehicle, with a name and a cost per kilometer.
    """
    
    # Fields
    name            = models.CharField(max_length=250, verbose_name="Nom")
    cost_per_km     = models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Coût kilométrique")
    default_pay     = models.BooleanField(default=False, verbose_name="Le conducteur paie")
    display         = models.BooleanField(default=True, verbose_name="Afficher dans le formulaire de calcul")
    
    def __str__(self):
        return '%s'%self.name
    
    class Meta:
        permissions = [('financial','Can view vehicle financial resume'),]
    
    
class VehicleEquipmentLink(models.Model):
    """
    This model make a link between vehicle and equipment. This allow to check the payment for each vehicles on associated category
    """
    
    vehicle_type    = models.ForeignKey(Vehicle, on_delete=models.PROTECT, verbose_name="Type")
    equipment       = models.ForeignKey(gm.Equipment, on_delete=models.CASCADE, verbose_name="Équipement")
    km_start        = models.ForeignKey(gm.EquipmentMeta, on_delete=models.PROTECT, related_name="link_km_start", verbose_name="Km départ")
    km_end          = models.ForeignKey(gm.EquipmentMeta, on_delete=models.PROTECT, related_name="link_km_end", verbose_name="Km arrivée")
    
    def save(self, *args, **kwargs):
        
        if self.km_start.equipment != self.equipment or self.km_end.equipment != self.equipment:
            raise ValueError("Related meta do not belong to equipement!")

        super().save(*args, **kwargs)
        
class VehicleTrackingCheck(models.Model):
    """
    This is a check of tracking by the responsible
    """
    
    person          = models.ForeignKey(gm.Person, on_delete=models.CASCADE, verbose_name="Vérificateur")
    tracking        = models.ForeignKey(gm.EquipmentTracking, on_delete=models.CASCADE, verbose_name="Tracking")
    date            = models.DateField(default=timezone.now, verbose_name="Date")
        
    class Meta:
        unique_together = (('person','tracking'))

vehicles/templates/vehicles/financial.html
{% extends "vehicles/template.html" %}
{% load gafc_tags %}

{% block pagename %} Véhicules - Finances {% endblock %}

{% block content %}
<div class="row">
    <div class="card col-12">
        <h5 class="card-header"> Paiements à encaisser </h5>
        <div class="card-body">
            <div class="row">
                <h6 class="col-1"> ID </h6>
                <h6 class="col-2"> Date </h6>
                <h6 class="col-2"> Contrepartie </h6>
                <h6 class="col-2"> Encodé par </h6>
                <h6 class="col-2"> Événement </h6>
                <h6 class="col-1"> Catégorie </h6>
                <h6 class="col-1"> Méthode </h6>
                <h6 class="col-1 text-right">Montant</h6>
            </div>
            {% for p in payments %}
            <div class="row {% cycle 'bg-light' '' %} pt-1 pb-1">
                <div class="col-1"><a href="{% url 'payment' p.id %}">P{{ p.id }}</a></div>
                <div class="col-2">{{ p.pay_done|date:'d/m/Y' }}</div>
                <div class="col-2"><a href="{% url 'person' p.person.id %}">{{ p.person }}</a></div>
                <div class="col-2"><a href="{% url 'person' p.encoder.id %}">{{ p.encoder }}</a></div>
                <div class="col-2">{% if p.event is not None %}<a href="{% url 'event' p.event.id %}">{{ p.event.title }}</a>{% endif %}</div>
                <div class="col-1"><a href="{% url 'category' p.category.id %}">{{ p.category }}</a></div>
                <div class="col-1">{{ p.method|payMethod }}</div>
                <div class="col-1 text-right {% if p.amount < 0 %}text-danger{% else %}text-success{% endif %}">{{ p.amount }}</div>
                {% if p.comment != '' %}
                    <h6 class="col-2"> Commentaire: </h6>
                    <div class="col-10">{{ p.comment }}</div>
                {% endif %}
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="card col-12">
        <h5 class="card-header"> Totaux </h5>
        <div class="card-body">
            <div class="row">
                <h6 class="col-2"> Catégorie </h6>
                {% for m in repart.TOTAL.1.items %}
                {% if m.0 != 'TOTAL' %}
                <h6 class="col text-right"> {{ m.0|payMethod }} </h6>
                {% endif %}
                {% endfor %}
                <h6 class="col text-right"> Total </h6>
            </div>
            
            {% for r in repart.items %}
            {% if r.0 != 'TOTAL' %}
            <div class="row">
                <div class="col-2"> <a href="{% url 'category' r.1.0.id %}">{{ r.1.0 }}</a> </div>
                {% for m in r.1.1.items %}
                {% if m.0 != 'TOTAL' %}
                <div class="col text-right"> {{ m.1|floatformat:2 }} </div>
                {% endif %}
                {% endfor %}
                <div class="col text-right"> {{ r.1.1.TOTAL|floatformat:2 }} </div>
            </div>
            {% endif %}
            {% endfor %}
            <div class="row">
                <div class="col-2"> Total </div>
                {% for m in repart.TOTAL.1.items %}
                {% if m.0 != 'TOTAL' %}
                <div class="col text-right"> {{ m.1|floatformat:2 }} </div>
                {% endif %}
                {% endfor %}
                <div class="col text-right"> {{ repart.TOTAL.1.TOTAL|floatformat:2 }} </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

vehicles/templates/vehicles/template.html
{% extends "template.html" %}
{% load gafc_tags %}

{% block title %}GUCEM - {% block pagename %}Minibus{% endblock %}{% endblock %}

{% block body %}

{% if request.user.is_authenticated %}

<nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-dark">
    <div class="navbar-brand">
        GUCEM - Minibus
    </div>
    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main_menu" aria-controls="main_menu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

    <!-- MENU -->
    <div class="collapse navbar-collapse" id="main_menu">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item"><a class="nav-link" href="{% url "vehicle_home" %}"> Calcul </a></li>
            {% if request.user.fullperms.vehicles.view_vehicle %}<li class="nav-item"><a class="nav-link" href="{% url "vehicle_view" %}"> Tableau </a></li>{% endif %}
            {% if request.user.fullperms.vehicles.financial %}
            <li class="nav-item"><a class="nav-link" href="{% url "vehicle_financial" %}"> Finances </a></li>
            <li class="nav-item"><a class="nav-link" href="{% url "vehicle_statistics" %}"> Statistiques </a></li>
            {% endif %}
            {% if request.user.fullperms.vehicles.change_vehicle %}
            <li class="nav-item"><a class="nav-link" href="{% url "vehicle_settings" %}"> Configuration </a></li>
            {% endif %}
        </ul>
    </div>

</nav>
{% endif %}

{% if messages %}
    {% for message in messages %}
    <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>
        {{ message }}
    </div>
    {% endfor %}
{% endif %}



<div class="container">
{% block content %}{% endblock %}
</div>
{% endblock %}

vehicles/templates/vehicles/view.html
{% extends "vehicles/template.html" %}
{% load gafc_tags %}

{% block pagename %} Véhicules {% endblock %}

{% block content %}

<div class="row">
    <div class="col-12">
    <nav>
        <ul class="pagination justify-content-center flex-wrap">
            {% for y in years %}
            <li class="page-item {% if y == year %}active{% endif %}"><a class="page-link"  href="{% url "vehicle_view_year" year=y %}">{{ y }}</a></li>
            {% endfor %}
        </ul>
    </nav>
    
    </div>
    <div class="card col-12">
        <h5 class="card-header"> Utilisation des véhicules </h5>
        <div class="card-body">
        
        <div class="row d-none d-md-flex">
            <h6 class="col-md-1"> Véhicule </h6>
            <h6 class="col-md-2"> Date </h6>
            <h6 class="col-md-2"> Raison </h6>
            <h6 class="col-md-1 text-right"> Départ </h6>
            <h6 class="col-md-1 text-right"> Arrivée </h6>
            <h6 class="col-md-1 text-right pl-0"> Parcouru</h6>
            <h6 class="col-md-1 text-right"> Coût théorique </h6>
            <h6 class="col-md-1 text-right"> PAF </h6>
            <h6 class="col-md-1 text-right"> Frais </h6>
            <h6 class="col-md-1 text-right"> Perçu </h6>
        </div>
            
        {% for d in data reversed %}
            <div class="row {% cycle 'bg-light' ''%}">
                <div class="col-8 col-md-1 pl-0">
                    <a class="btn btn-secondary p-1" data-toggle="collapse" data-target="#collapse-{{ forloop.counter }}">{% b_icon 'caret-down-square' %}</a>
                    {% if d.vehicle is not None %}
                    <a href="{% url 'equipment' d.vehicle.equipment.id %}">{{ d.vehicle.equipment.name }}</a>
                    {% endif %}
                </div>
                <div class="col-4 col-md-2">
                    {% if request.user.perms.change_equipmenttracking and d.tracking is not None%}
                        <a href="{% url "equipmenttracking" d.tracking.id %}">{{ d.date|date:'d/m/Y' }}</a>
                    {% else %}
                        {{ d.date|date:'d/m/Y' }}
                {% endif %}
                {% if d.checked is not None %}
                    {% if d.checked %}
                        <br /><span class="text-success">{{ d.check.date|date:'d/m/Y' }}</span> <a href="{% url 'vehicle_view_action' 'delcheck' d.tracking.id %}" class="text-danger">{% b_icon 'x-square-fill' 24 %}</a>
                    {% else %}
                        <a href="{% url 'vehicle_view_action' 'addcheck' d.tracking.id %}" class="text-success">{% b_icon 'check-square-fill' 24 %}</a>
                    {% endif %}
                {% endif %}
                </div>
                <div class="col-12 col-md-2">{% if d.tracking.event is not None %}<a href="{% url 'event' d.tracking.event.id %}">{{ d.tracking.event.title }}</a>{% elif d.tracking is None %} <a href="{% url 'category' d.category.id %}">{{ d.category.name }}</a> {% endif %}</div>
                <div class="col-6 col-md-1 text-right">
                    {% if d.km_in is not None %}{{ d.km_in }}{% endif %}<br />
                    {% if d.km_diff != 0 %}<b class="text-danger">{% if d.km_diff > 0 %}+{% endif %}{{ d.km_diff }}</b>{% endif %}
                </div>
                <div class="col-6 col-md-1 text-right">&nbsp;{% if d.km_out is not None %}{{ d.km_out }}{% endif %}
                </div>
                <div class="col-6 col-md-1 text-right">&nbsp;{% if d.km is not None %}{{ d.km }}{% endif %}</div>
                <div class="col-6 col-md-1 text-right">
                    {% if d.th_cost is not None %}{{ d.th_cost|floatformat:2 }}<br />{% endif %}
                    {% if d.diff is not None %}<b class="{% if d.diff >= 0 %}text-success{% elif d.diff < -5 %}text-danger{% else %}text-warning{% endif %}">{% if d.diff > 0 %}+{% endif %}{{ d.diff|floatformat:2 }}</b>{% endif %}
                </div>
                <div class="col-6 col-md-1 text-right text-success">{% if d.payed != 0 %}{{ d.payed|floatformat:2 }}{% endif %}</div>
                <div class="col-6 col-md-1 text-right text-danger"> {% if d.fee != 0 %}{{ d.fee|floatformat:2 }}{% endif %}</div>
                <div class="col-6 col-md-1 text-right font-weight-bold {% if d.eff_payed > 0 %}text-success{% elif d.eff_payed < 0 %}text-danger{% endif %}">{% if d.eff_payed > 0 %}+{% endif %}{{ d.eff_payed|floatformat:2 }}</div>
                {% if d.tracking is not None and d.tracking.comment != '' %}
                <h6 class="col-md-2"> Commentaire: </h6>
                <div class="col-md-10"> {{ d.tracking.comment }} </div>
                {% endif %}
                
                <div class="collapse col-12" id="collapse-{{ forloop.counter }}">
                    <div class="row">
                    {% if d.tracking is not None %}
                        <h6 class="col-md-4"> Encodé par: </h6>
                        <div class="col-md-8"> <a href="{% url 'person' d.tracking.person.id %}">{{ d.tracking.person }}</a> </div>
                        
                        {% for c in d.tracking.vehicletrackingcheck_set.all %}
                        <h6 class="col-md-4"> {% ifchanged %}Vérifié par:{% endifchanged %} </h6>
                        <div class="col-md-4 col-6"><a href="{% url 'person' c.person.id %}">{{ c.person }}</a> </div>
                        <div class="col-md-4 col-6"> {{ c.date|date:'d/m/Y' }} </div>
                        {% endfor %}
                    {% endif %}
                        <div class="col-12">
                            {% if d.payments|length != 0 %}
                            <div class="row d-none d-md-flex">
                                <h6 class="col-1 pl-1 pr-0"></h6>
                                <h6 class="col-2"> Encodé par </h6>
                                <h6 class="col-2"> Contrepartie </h6>
                                <h6 class="col-3"> Raison </h6>
                                <h6 class="col-2"> Encaissé </h6>
                                <h6 class="col-1"> Méthode </h6>
                                <h6 class="col-1 pl-0 pr-1 text-right"> Montant </h6>
                            </div>
                            {% endif %}
                            {% for p in d.payments %}
                            <div class="row">
                                <div class='col-12 d-md-none'><hr /></div>
                                <div class="col-1 pl-1 pr-0">{% if p.external %}<a href="{% url 'payment' p.id %}">P{{p.id}}</a>{% else %}<a href="{% url 'transfer' p.id %}">T{{p.id}}</a>{% endif %}</div>
                                <div class="col-6 col-md-2"><a href="{% url 'person' p.encoder.id %}">{{ p.encoder }}</a></div>
                                <div class="col-6 col-md-2"><a href="{% if p.external %}{% url 'person' p.payee.id %}{% else %}{% url 'category' p.payee.id %}{% endif %}">{{ p.payee }}</a></div>
                                <div class="col-md-3">{{ p.comment }}</div>
                                <div class="col-8 col-md-2">{% if p.cashing is not None %}{{ p.cashing.id }} ({{ p.cashing.date|date:'d/m/Y' }}){% endif %}</div>
                                <div class="col-8 col-md-1">{{ p.method|payMethod }}</div>
                                <div class="col-4 col-md-1 pl-1 pr-1 text-right {% if p.amount > 0 %}text-success{% elif p.amount < 0 %}text-danger{% endif %}">{{ p.amount|floatformat:2 }}</div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
            
        </div>
    </div>
</div>


{% endblock %}