gafc/urls.py
# -*- coding: utf-8 -*-
#
# This file is part of GAFC.
#
# GAFC is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# GAFC is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with GAFC. If not, see <https://www.gnu.org/licenses/>. 
#
# 2022 - William Chèvremont

"""
GAFC main URL router
"""

from django.urls import path, re_path, register_converter
from django.views.decorators.csrf import csrf_exempt
from .views import callback, categories, equipments, events, financials, home, logins, persons, settings, dashboard, jsondata, permissions, mailings
from datetime import datetime


class DateConverter:
    """
    Custom converter for dates in url
    """
    regex = '\d{4}-\d{2}-\d{2}'

    def to_python(self, value):
        """
        Convert the date to python date
        :param value: Date in Y-m-d format
        :type value: str
        :return date
        :rtype datetime.datetime
        """
        return datetime.strptime(value, '%Y-%m-%d')

    def to_url(self, value):
        """
        Convert the date to string
        :param value: Date
        :type value: datetime.datetime or datetime.date
        :return date
        :rtype str
        """
        return value.strftime('%Y-%m-%d')
    
register_converter(DateConverter, 'dateYmd')


urlpatterns = [
    # Home
    path('', home.HomeView.as_view() , name='home'),
    path('season/set', home.SetSeasonView.as_view(), name='set_season'),
    
    # Dashboard
    path('dashboard', dashboard.DashboardView.as_view(), name='dashboard'),
    path('dashboard/<dateYmd:today>', dashboard.DashboardView.as_view(), name='dashboard'),
    
    path('dashboard/plot/members_ages', dashboard.DashboardGraphsView.as_view(action='members_by_age'), name="dashboard_members_ages"),
    path('dashboard/plot/members_ages/<dateYmd:today>', dashboard.DashboardGraphsView.as_view(action='members_by_age'), name="dashboard_members_ages"),
    
    path('dashboard/plot/members_timeline', dashboard.DashboardGraphsView.as_view(action='adhesions_timeline'), name="dashboard_adhesions_timeline"),
    path('dashboard/plot/members_timeline/<dateYmd:today>', dashboard.DashboardGraphsView.as_view(action='adhesions_timeline'), name="dashboard_adhesions_timeline"),
    
    path('dashboard/plot/members_firstyear', dashboard.DashboardGraphsView.as_view(action='members_by_firstyear'), name="dashboard_members_firstyear"),
    path('dashboard/plot/members_firstyear/<dateYmd:today>', dashboard.DashboardGraphsView.as_view(action='members_by_firstyear'), name="dashboard_members_firstyear"),
    
    path('dashboard/plot/mixity/<int:sid>', dashboard.MixityGraphsView.as_view(), name='mixityPlot'),
    path('dashboard/plot/mixity/<int:sid>/<int:catid>', dashboard.MixityGraphsView.as_view(), name='mixityPlot'),
    
    
    # Json data
    path('jsondata/persons', jsondata.JsonDataView.as_view(action='persons'), name="persons_json"),
    path('jsondata/events', jsondata.JsonDataView.as_view(action='events'), name="events_json"),
    path('jsondata/events/all', jsondata.JsonDataView.as_view(action='events'), {'allevt': True}, name="events_json_all"),
    path('jsondata/payments', jsondata.JsonDataView.as_view(action='payments'), name="payments_json"),
    
    # Events
    path('event/calendar', events.EventsView.as_view(), name='list_events'),
    path('event/calendar/<int:year>/<int:month>', events.EventsView.as_view(), name='list_events'),
    path('event/<int:event_id>',events.EventView.as_view(), name='event'), 
    path('event/<int:event_id>/licenses', events.EventLicenseView.as_view(), name='event_licenses'),
    path('event/participation/<int:event_id>', events.EventParticipationView.as_view(), name='event_participation'),
    path('event/<int:eid>/export',events.EventExportView.as_view(), name='event_export'),   
    
    path('events/calendar/<int:cid>', events.EventICSCalendarView.as_view()),
    
    # Login Logout, Register, ...
    path('login', logins.LoginView.as_view(), name='login'),
    path('logout', logins.LogoutView.as_view(), name='logout'),
    path('register', logins.RegisterView.as_view(), name='new_account'),
    path('lost_password', logins.LostPasswordRequestView.as_view(), name="lost_password"),
    path('new_lost_password/<int:id>/<str:token>', logins.NewPasswordProcessView.as_view(), name="new_lost_password"),
    
    # Persons
    path('person/list', persons.PersonListView.as_view(), name='list_persons'),
    path('person/list/<int:page>',persons.PersonListView.as_view(), name='list_persons'),
    re_path(r'^person/list/(?P<name_first_letter>[a-zA-Z])$',persons.PersonListView.as_view(), name='list_persons'),
    re_path(r'^person/list/(?P<name_first_letter>[a-zA-Z])/(?P<page>[0-9]+)$',persons.PersonListView.as_view(), name='list_persons'),
    path('person/staffing',persons.PersonsStaffingView.as_view(), name='staffing_all'),
    path('person/<int:person_id>', persons.PersonView.as_view(), name='person'),
    path('person/var_person_id', persons.PersonView.as_view(), name='person_js'),
    #path('import_members/', persons.upload_from_memberlist, name='import_members'),
    #path('import_licenses/', persons.import_licenses, name='import_licenses'),
    
    # Mailing list
    path('mailing/', mailings.MailingListListView.as_view(), name='mailings'),
    path('mailing/<str:mlname>', mailings.MailingListView.as_view(), name='mailing'),
    
    # Permissions
    path('permissions/', permissions.PermissionsView.as_view(), name='permissions'),
    path('permissions/<int:group_id>', permissions.PermissionsGroupView.as_view() , name="permission_group"),
    
    # Categories
    path('category/<int:category_id>/events/export', categories.CategoryEventsCSVExportView.as_view(), name='category_events_export'),
    path('category/<int:category_id>/stats/participations', categories.CategoryParticipationGraphView.as_view() , name='category_p_repartition'),
    path('category/<int:category_id>', categories.CategoryView.as_view(), name='category'),
    path('category/<int:category_id>/events/edit', categories.CategoryEventsEdit.as_view(), name='category_events_edit'),
    path('category/<int:category_id>/events/edit/<int:year>/<int:month>', categories.CategoryEventsEdit.as_view(), name='category_events_edit'),
    
    # Cashing
    path('financials/cashing/list', financials.CashingListView.as_view(), name='financial'),
    path('financials/cashing/mylist', financials.CashingUserView.as_view(), name='financial_refund' ),
    path('financials/cashing/list/<int:year>', financials.CashingListView.as_view(), name='financial'),
    path('financials/cashing/<int:cid>', financials.CashingView.as_view(), name='cashing'),
    path('financials/cashing/file/<int:fid>', financials.CashingFileDownloadView.as_view(), name='cashing_file'),
    path('financials/cashing/signature/<int:fid>', financials.CashingSignatureFileDownloadView.as_view(), name='cashing_signature'),
    
    # Forseenbalance
    path('financials/forseenbalance/list', financials.ForseenBalanceListView.as_view(), name="fin_forseenbalances"),
    path('financials/forseenbalance/<int:balid>', financials.ForseenBalanceView.as_view(), name="fin_forseenbalance"),
    
    #Bank account operation
    path('financials/bankaccount/', financials.AccountOperationView.as_view(), name='accountoperations'),
    path('financials/bankaccount/balances', financials.AccountBalanceView.as_view(), name='accountbalance'),
    path('financials/bankaccount/<int:year>', financials.AccountOperationView.as_view(), name='accountoperations'),
    path('financials/bankaccount/processfile', financials.AccountOperationFileView.as_view(), name='accountoperations_file'),
    
    # Financial category manager
    path('financial/categories', financials.FinancialCategoryView.as_view(), name='fincat'),
    
    # Single operations
    path('financials/payment/<int:payment_id>', financials.PaymentView.as_view(), name='payment'),
    path('financials/transfer/<int:tid>', financials.TransferView.as_view(), name='transfer'),
    path('financials/operation/<int:opid>', financials.OperationView.as_view(), name='operation'),
    
    # Helloasso
    path('financials/payments/helloasso', financials.HelloassoPaymentView.as_view(), name='helloasso_payments'),
    
    # Balances
    path('financials/balance/daily', financials.BalanceView.as_view(action='balance_tmp'), name="fin_balance"),
    path('financials/balance/done', financials.BalanceView.as_view(action='balance_done'), name="fin_balance_done"),
    
    # Equipments
    path('equipment/list', equipments.EquipmentListView.as_view(), name='list_equipment'),
    path('equipment/<int:eqid>', equipments.EquipmentView.as_view(), name='equipment'),
    path('equipment/picture/<int:picture_id>', equipments.EquipmentPictureView.as_view() , name='equipment_picture'),
    path('equipment/calendar', equipments.EquipmentCalendarView.as_view(), name='calendar_equipment'),
    path('equipment/calendar/<int:year>/<int:month>', equipments.EquipmentCalendarView.as_view(), name='calendar_equipment'),
    path('equipment/group/<int:eqgrp_id>', equipments.EquipmentGroupView.as_view(), name='equipment_grp'),
    path('equipment/tracking/<int:tracking_id>', equipments.EquipmentTrackingView.as_view(), name='equipmenttracking'),
    
    # Settings
    path('settings', settings.SettingsView.as_view(), name='settings'),
    
    #Export
    path('export/season_archive/<int:sid>', settings.SeasonArchiveView.as_view(), name='season_archive'),

gucem/urls.py
# -*- coding: utf-8 -*-
#
# This file is part of GAFC.
#
# GAFC is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# GAFC is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with GAFC. If not, see <https://www.gnu.org/licenses/>. 
#
# 2022 - William Chèvremont

"""gucem URL Configuration
"""

from django.urls import include,path, re_path
from django.conf.urls import handler404, handler500, handler403
from .views import redirect_view
from django.conf import settings
from django.conf.urls.static import static

from gafc.views import handlers as gv
import gucem.settings as gset

urlpatterns = [
    path('',redirect_view),
    path('gafc/main/', include('gafc.urls'), name="intranet"),
    path('gafc/minibus/', include('vehicles.urls'), name="minibus"),
    path('gafc/formation/', include('formation.urls'), name='formation'),
    path('gafc/keys/', include('keys.urls'), name='keys'),
    re_path('gafc/[a-z]*$',redirect_view),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) # Only for development. Need static file server for production;

handler403 = gv.handler403
handler404 = gv.handler404
handler500 = gv.handler500

if gset.DEBUG:
    try:
        import debug_toolbar
        urlpatterns += [ path('__debug__/', include(debug_toolbar.urls)), ]
    except Exception as e:
        print(e)

gafc/models/gafc.py
# -*- coding: utf-8 -*-
#
# This file is part of GAFC.
#
# GAFC is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# GAFC is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with Foobar. If not, see <https://www.gnu.org/licenses/>. 
#
# 2022 - William Chèvremont


"""
Generic models
"""


from django.db import models
from .user import Person
#import gucem.settings

class Season(models.Model):
    name        = models.CharField(max_length=30, verbose_name='Saison', unique=True)
    is_default  = models.BooleanField(default=False, verbose_name='Default')
    
    def save(self, *args, **kwargs): # Ensure one defaut Season
        try:
            temp = Season.objects.get(is_default=True)
            if self.is_default and self != temp:
                temp.is_default = False
                super(Season, temp).save()
        except Season.DoesNotExist:
            self.is_default = True;
            
        super(Season, self).save(*args, **kwargs)
        
    class Meta:
        default_permissions = ('add','view','change','delete')
        
    def __str__(self):
        return str(self.name)
    
    
class StaffEmail(models.Model):
    email       = models.EmailField(unique=True)
    authorized  = models.ManyToManyField('Person')
    noauth      = models.BooleanField(default=False, verbose_name='Adresse "noreply"')
    
    class Meta:
        default_permissions = ('add', 'view', 'change', 'delete', 'send_noauth')
        
    def __str__(self):
        return self.email
    
class StaffEmailAlias(models.Model):
    email       = models.EmailField()
    main        = models.ForeignKey(StaffEmail, on_delete=models.CASCADE)
    
    
class EmailModel(models.Model):
    title       = models.CharField(max_length=250, verbose_name="Titre")
    content     = models.TextField(verbose_name="Contenu")
    
    class Meta:
        default_permissions = ('add', 'view', 'change', 'delete')
        
class FinancialCategoryTree(models.Model):
    name        = models.CharField(max_length=100, verbose_name='Nom')
    toplevel    = models.ForeignKey('FinancialCategoryTree', null=True, on_delete=models.PROTECT, verbose_name="Parent")
    
    def __str__(self):
        return self.name
    
class FinancialCategory(models.Model):
    tree        = models.ForeignKey(FinancialCategoryTree, on_delete=models.PROTECT, verbose_name="Parent")
    name        = models.CharField(max_length=100, verbose_name='Nom')
    
    def __str__(self):
        return self.name
    
    class Meta:
        default_permissions = ('add', 'change', 'delete', 'view', 'balance')        


class Category(models.Model):
    name        = models.CharField(max_length=30, verbose_name='Catégorie')
    is_global   = models.BooleanField(verbose_name='Global', default=False)
    allowed_fincat = models.ManyToManyField('FinancialCategory', related_name='allowed_categories')
    default_fincat = models.ForeignKey('FinancialCategory', null=True, on_delete=models.SET_NULL)
    
    def __str__(self):
        return self.name
    
    class Meta:
        default_permissions = ('add','change','delete', 'view', 'financial')
        
    @property
    def finids(self):
        return [ f.id for f in self.allowed_fincat.all() ]
    

class Staff(models.Model):
    person      = models.ForeignKey(Person, on_delete=models.CASCADE, verbose_name='Encadrant')
    category    = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Catégorie')
    season      = models.ForeignKey(Season, on_delete=models.CASCADE, verbose_name='Saison')
    level       = models.CharField(max_length=3,  choices=[('1CO', 'Co-encadrant'),
                                                           ('2SU', 'Encadrant'),
                                                           ('3PR', 'Professionnel')],)
    
    class Meta:
        unique_together = (('person','category','season'))
        default_permissions = ('add','change','delete')
        
    @property
    def valid_validations(self):
        r = []
        for v in self.validation_set.all():
            if v.date_end is None:
                r += [v,]
        return r
    
    def save(self, *args, **kwargs):
        if self.pk is not None and len(self.valid_validations) > 0:
            raise ValueError('Can\'t change staff subscription after validation')
        
        return super().save(*args, **kwargs)

gafc/templates/gafc/equipmenttracking.html
{% extends "gafc/template.html" %}
{% load gafc_tags %}
{% load crispy_forms_tags %}

{% block pagename %} {{ t.equipment.name }} {% endblock %}

{% block content %}
<h3> Suivi de l'équipement {{ t.equipment.name }} </h3>

<div class="row">
    <div class="card col-12 col-lg-8">
        <h5 class="card-header">Modification</h5>
        <div class="card-body">
            <div class="row">
                <div class="col-sm-4">Équipement: </div>
                <div class="col-sm-8">{{ t.equipment.name }}</div>
            </div>
            <div class="row">
                <div class="col-sm-4">Description de l'équipement: </div>
                <div class="col-sm-8">{{ t.equipment.description|linebreaks }}</div>
            </div>
        
            {% crispy self.forms.add_tracking %}
            
        </div>
    </div>
</div>


{% endblock %}

gafc/templates/gafc/settings.html
{% extends "gafc/template.html" %}
{% load crispy_forms_tags %}
{% load gafc_tags %}

{% block pagename %} Configuration {% endblock %}

{% block content %}

<h3> Configuration </h3>

<div class="row">

    <div class="card col-md-6"><h5 class="card-header"> 
            <a class="btn btn-light p-1 d-md-none" data-toggle="collapse" href="#card-body-info" >{% b_icon 'caret-down-square' 25 %}</a> Informations
        </h5>
        <div class="card-body collapse dont-collapse-sm" id="card-body-info">
            <table>
                <tr>
                    <th> Version :</th>
                    <td>{{ version }}</td>
                </tr>
                <tr>
                    <th> Date : </th>
                    <td> {{ version_date|date:'d F Y' }} </td>
                </tr>
            </table>
        </div>
    </div>
    
    <div class="col-md-6 card"><h5 class="card-header">
            <a class="btn btn-light p-1 d-md-none" data-toggle="collapse" href="#card-body-fede" >{% b_icon 'caret-down-square' 25 %}</a> Fédérations
        </h5>
        <div class="card-body collapse dont-collapse-sm" id="card-body-fede">
            {% if 'add_federation' in self.forms %}
            <a class="btn btn-secondary" data-toggle="collapse" href="#formAddFederation" role="button" aria-expanded="false" aria-controls="formAddFederation"> Ajouter une fédération </a>

            <div class="collapse {% if form_f.errors %}show{% endif %}" id="formAddFederation">
                {% crispy self.forms.add_federation %}
            </div>
            {% endif %}

            <div class="row">
                <h6 class="col-8">Fédération</h6>
                <h6 class="col-4">Acronyme</h6>
            </div>
            
            {% for f in feds %}
            <div class="row pb-1 pt-1 {% cycle 'bg-light' '' %}">
                <div class="col-8">{{ f.name }}</div>
                <div class="col-4">{{ f.acronym }}</div>
            </div>
            {% endfor %}

        </div>
    </div>

    {% if request.user.perms.view_category %}
    <div class="col-md-6 card"><h5 class="card-header">
            <a class="btn btn-light p-1 d-md-none" data-toggle="collapse" href="#card-body-categories" >{% b_icon 'caret-down-square' 25 %}</a> Catégories
        </h5>
        <div class="card-body collapse dont-collapse-sm" id="card-body-categories">
            {% if  'save_category' in self.forms %}
            <a class="btn btn-secondary" data-toggle="collapse" href="#formAddCategory" role="button" aria-expanded="false" aria-controls="formAddCategory"> Ajouter une catégorie </a>

            <div class="collapse {% if form_c.errors %}show{% endif %}" id="formAddCategory">
            {% crispy self.forms.save_category %}
            </div>
            {% endif %}

            <div class="row">
                <h6 class="col-10">Nom</h6>
                <h6 class="col-2 text-nowrap">Global</h6>
            </div>
            {% for c in cats %}
            <div class="row pb-1 pt-1 {% cycle 'bg-light' '' %}">
                <div class="col-10"><a href="{% url "category" c.id %}">{{ c.name }}</a></div>
                <div class="col-2 text-center">{% if c.is_global %}{% b_icon 'check-square-fill' %}{% else %}{% b_icon 'square' %}{% endif %}</div>
            </div>
            {% endfor %}

        </div>
    </div>
    {% endif %}

    {% if form_s or form_s_default or request.user.perms.view_season %}
    <div class="card col-md-6"><h5 class="card-header">
            <a class="btn btn-light p-1 d-md-none" data-toggle="collapse" href="#card-body-seasons" >{% b_icon 'caret-down-square' 25 %}</a> Saisons
        </h5>
        <div class="card-body collapse dont-collapse-sm" id="card-body-seasons">
        
            {% if 'add_season' in self.forms %}
            {% crispy self.forms.add_season %}
            {% endif %}

            {% if 'set_season' in self.forms %}
            {% crispy self.forms.set_season %}
            {% endif %}
            
            {% if request.user.perms.view_season %}
            <h5> Archives </h5>

            {% for s in seasons %}
            <div class="row">
                <a class="col-12" href="{% url 'season_archive' s.id %}"> {{ s.name }} </a>
            </div>
            {% endfor %}
            {% endif %}
            
            {% if request.user.perms.view_staff %}
            <h5> Liste des encadrants </h5>

            {% for s in seasons %}
            <div class="row">
                <a class="col-12" href="{% url 'staff_list' s.id %}"> {{ s.name }} </a>
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
    {% endif %}
    
    {% if request.user.perms.view_staffemail %}
    <div class="col-md-6 card"><h5 class="card-header">
            <a class="btn btn-light p-1 d-md-none" data-toggle="collapse" href="#card-body-emails" >{% b_icon 'caret-down-square' 25 %}</a> Emails
        </h5>
        <div class="card-body collapse dont-collapse-sm" id="card-body-emails">
            {% if 'save_staffemail' in self.forms %}
            <div class="row">
                <a href="#formAddStaffEmail" data-toggle="collapse" class="btn btn-secondary">Ajouter une adresse d'envoi</a>
                <div class="col-12 collapse" id="formAddStaffEmail">
                    {% crispy self.forms.save_staffemail %}
                </div>
            </div>
            {% endif %}
        
            {% if 'save_staffemailalias' in self.forms %}
            <div class="row">
                <a href="#formAddStaffEmailAlias" data-toggle="collapse" class="btn btn-secondary">Ajouter un alias</a>
                <div class="col-12 collapse" id="formAddStaffEmailAlias">
                    {% crispy self.forms.save_staffemailalias %}
                </div>
            </div>
            {% endif %}
        
            {% if 'save_staffemailsender' in self.forms %}
            <div class="row">
                <a href="#formAddStaffEmailSender" data-toggle="collapse" class="btn btn-secondary">Ajouter un compte autorisé</a>
                <div class="col-12 collapse" id="formAddStaffEmailSender">
                    {% crispy self.forms.save_staffemailsender %}
                </div>
            </div>
            {% endif %}
        
            {% for e in staffmail %}
                <div class="row">
                    <span class="col-12 btn btn-secondary" data-toggle="collapse" href="#formChangeEmail{{ forloop.counter }}" role="button" aria-expanded="false" aria-controls="formChangeEmail{{ forloop.counter }}">{{ e.email }}</span>
            
                    <div class="collapse col-12" id="formChangeEmail{{ forloop.counter }}">
                        <div class="row">
                            <b class="col-12">Alias</b>
                        </div>
                        {% for a in e.staffemailalias_set.all %}
                        <div class="row">
                            <div class="col-md-8">{{ a.email }}</div>
                            <div class="col-md-4">
                            {% if 'delete_staffemailalias' in self.forms %}
                            {% setFieldValue self.forms.delete_staffemailalias inst=a.pk %}
                            {% crispy self.forms.delete_staffemailalias %}
                            {% endif %}
                            </div>
                        </div>           
                        {% endfor %}
                        <div class="row">
                            <b class="col-12">Adhérents autorisées</b>
                        </div>
                        {% for a in e.authorized.all %}
                        <div class="row">
                            <div class="col-md-8"><a href="{% url 'person' a.id %}">{{ a }}</a></div>
                            <div class="col-md-4">
                            {% if 'delete_staffemailsender' in self.forms %}
                            {% setFieldValue self.forms.delete_staffemailsender main=e.pk sender=a.pk %}
                            {% crispy self.forms.delete_staffemailsender %}
                            {% endif %}
                            </div>
                        </div>           
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    
    {% endif %}
                        
    {% if request.user.perms.view_cashingabandonvalidator %}
    
    <div class="col-md-6 card">
        <h5 class="card-header"> <a class="btn btn-light p-1 d-md-none" data-toggle="collapse" href="#card-body-fisc" >{% b_icon 'caret-down-square' 25 %}</a> Signatures attestations fiscales </h5>
            
        <div class="card-body collapse dont-collapse-sm" id="card-body-fisc">
            {% if 'add_abandonvalidator' in self.forms %}
            <a class="btn btn-secondary" data-toggle="collapse" href="#formAddAbandonV" role="button" aria-expanded="false" aria-controls="formAddAbandonV"> Ajouter une personne autorisée </a>

            <div class="collapse {% if self.forms.add_abandonvalidator.errors %}show{% endif %}" id="formAddAbandonV">
                {% crispy self.forms.add_abandonvalidator %}
            </div>
            {% endif %}
    
            {% if 'add_abandonvalidator_file' in self.forms %}
            <a class="btn btn-secondary" data-toggle="collapse" href="#formAddAbandonI" role="button" aria-expanded="false" aria-controls="formAddAbandonI"> Ajouter image signature </a>
        
            <div class="collapse {% if self.forms.add_abandonvalidator_file.errors %}show{% endif %}" id="formAddAbandonI">
                {% crispy self.forms.add_abandonvalidator_file %}
            </div>
            {% endif %}
    
            {% for v in fiscal_validators %}
            <div class="row">
                <div class="col-md-6">{{ v.person }}</div>
                <div class="col-10 col-md-5">{{ v.titre }}</div>
                <div class="col-2 col-md-1">
                {% if 'delete_cashing_abandon_validator' in self.forms %}
                {% setFieldValue self.forms.delete_cashing_abandon_validator inst=v.pk %}
                {% crispy self.forms.delete_cashing_abandon_validator %}
                {% endif %}
                </div>
            
                {% if v.has_image %}
                <div class="col-10">
                    <img src="{% url 'cashing_signature' v.person_id %}" width="70%" />
                </div>
                <div class="col-2 col-md-1">
                {% if 'delete_cashingabandonvalidator_file' in self.forms %}
                {% setFieldValue self.forms.delete_cashingabandonvalidator_file inst=v.pk %}
                {% crispy self.forms.delete_cashingabandonvalidator_file %}
                {% endif %}
                </div>                
                {% endif %}
            </div>
            {% endfor %}
            
        </div>
    </div>                            
                                            
    {% endif %}
    
</div>

{% endblock %}