gafc/urls.py
# -*- coding: utf-8 -*-
#
# This file is part of GAFC.
#
# GAFC is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# GAFC is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with GAFC. If not, see <https://www.gnu.org/licenses/>. 
#
# 2022 - William Chèvremont

"""
GAFC main URL router
"""

from django.urls import path, re_path, register_converter
from django.views.decorators.csrf import csrf_exempt
from .views import callback, categories, equipments, events, financials, home, logins, persons, settings, dashboard, jsondata, permissions, mailings
from datetime import datetime


class DateConverter:
    """
    Custom converter for dates in url
    """
    regex = '\d{4}-\d{2}-\d{2}'

    def to_python(self, value):
        """
        Convert the date to python date
        :param value: Date in Y-m-d format
        :type value: str
        :return date
        :rtype datetime.datetime
        """
        return datetime.strptime(value, '%Y-%m-%d')

    def to_url(self, value):
        """
        Convert the date to string
        :param value: Date
        :type value: datetime.datetime or datetime.date
        :return date
        :rtype str
        """
        return value.strftime('%Y-%m-%d')
    
register_converter(DateConverter, 'dateYmd')


urlpatterns = [
    # Home
    path('', home.HomeView.as_view() , name='home'),
    path('season/set', home.SetSeasonView.as_view(), name='set_season'),
    
    # Dashboard
    path('dashboard', dashboard.DashboardView.as_view(), name='dashboard'),
    path('dashboard/<dateYmd:today>', dashboard.DashboardView.as_view(), name='dashboard'),
    
    path('dashboard/plot/members_ages', dashboard.DashboardGraphsView.as_view(action='members_by_age'), name="dashboard_members_ages"),
    path('dashboard/plot/members_ages/<dateYmd:today>', dashboard.DashboardGraphsView.as_view(action='members_by_age'), name="dashboard_members_ages"),
    
    path('dashboard/plot/members_timeline', dashboard.DashboardGraphsView.as_view(action='adhesions_timeline'), name="dashboard_adhesions_timeline"),
    path('dashboard/plot/members_timeline/<dateYmd:today>', dashboard.DashboardGraphsView.as_view(action='adhesions_timeline'), name="dashboard_adhesions_timeline"),
    
    path('dashboard/plot/members_firstyear', dashboard.DashboardGraphsView.as_view(action='members_by_firstyear'), name="dashboard_members_firstyear"),
    path('dashboard/plot/members_firstyear/<dateYmd:today>', dashboard.DashboardGraphsView.as_view(action='members_by_firstyear'), name="dashboard_members_firstyear"),
    
    path('dashboard/plot/mixity/<int:sid>', dashboard.MixityGraphsView.as_view(), name='mixityPlot'),
    path('dashboard/plot/mixity/<int:sid>/<int:catid>', dashboard.MixityGraphsView.as_view(), name='mixityPlot'),
    
    
    # Json data
    path('jsondata/persons', jsondata.JsonDataView.as_view(action='persons'), name="persons_json"),
    path('jsondata/events', jsondata.JsonDataView.as_view(action='events'), name="events_json"),
    path('jsondata/events/all', jsondata.JsonDataView.as_view(action='events'), {'allevt': True}, name="events_json_all"),
    path('jsondata/payments', jsondata.JsonDataView.as_view(action='payments'), name="payments_json"),
    
    # Events
    path('event/calendar', events.EventsView.as_view(), name='list_events'),
    path('event/calendar/<int:year>/<int:month>', events.EventsView.as_view(), name='list_events'),
    path('event/<int:event_id>',events.EventView.as_view(), name='event'), 
    path('event/<int:event_id>/licenses', events.EventLicenseView.as_view(), name='event_licenses'),
    path('event/participation/<int:event_id>', events.EventParticipationView.as_view(), name='event_participation'),
    path('event/<int:eid>/export',events.EventExportView.as_view(), name='event_export'),   
    
    path('events/calendar/<int:cid>', events.EventICSCalendarView.as_view()),
    
    # Login Logout, Register, ...
    path('login', logins.LoginView.as_view(), name='login'),
    path('logout', logins.LogoutView.as_view(), name='logout'),
    path('register', logins.RegisterView.as_view(), name='new_account'),
    path('lost_password', logins.LostPasswordRequestView.as_view(), name="lost_password"),
    path('new_lost_password/<int:id>/<str:token>', logins.NewPasswordProcessView.as_view(), name="new_lost_password"),
    
    # Persons
    path('person/list', persons.PersonListView.as_view(), name='list_persons'),
    path('person/list/<int:page>',persons.PersonListView.as_view(), name='list_persons'),
    re_path(r'^person/list/(?P<name_first_letter>[a-zA-Z])$',persons.PersonListView.as_view(), name='list_persons'),
    re_path(r'^person/list/(?P<name_first_letter>[a-zA-Z])/(?P<page>[0-9]+)$',persons.PersonListView.as_view(), name='list_persons'),
    path('person/staffing',persons.PersonsStaffingView.as_view(), name='staffing_all'),
    path('person/<int:person_id>', persons.PersonView.as_view(), name='person'),
    path('person/var_person_id', persons.PersonView.as_view(), name='person_js'),
    #path('import_members/', persons.upload_from_memberlist, name='import_members'),
    #path('import_licenses/', persons.import_licenses, name='import_licenses'),
    
    # Mailing list
    path('mailing/', mailings.MailingListListView.as_view(), name='mailings'),
    path('mailing/<str:mlname>', mailings.MailingListView.as_view(), name='mailing'),
    
    # Permissions
    path('permissions/', permissions.PermissionsView.as_view(), name='permissions'),
    path('permissions/<int:group_id>', permissions.PermissionsGroupView.as_view() , name="permission_group"),
    
    # Categories
    path('category/<int:category_id>/events/export', categories.CategoryEventsCSVExportView.as_view(), name='category_events_export'),
    path('category/<int:category_id>/stats/participations', categories.CategoryParticipationGraphView.as_view() , name='category_p_repartition'),
    path('category/<int:category_id>', categories.CategoryView.as_view(), name='category'),
    path('category/<int:category_id>/events/edit', categories.CategoryEventsEdit.as_view(), name='category_events_edit'),
    path('category/<int:category_id>/events/edit/<int:year>/<int:month>', categories.CategoryEventsEdit.as_view(), name='category_events_edit'),
    
    # Cashing
    path('financials/cashing/list', financials.CashingListView.as_view(), name='financial'),
    path('financials/cashing/mylist', financials.CashingUserView.as_view(), name='financial_refund' ),
    path('financials/cashing/list/<int:year>', financials.CashingListView.as_view(), name='financial'),
    path('financials/cashing/<int:cid>', financials.CashingView.as_view(), name='cashing'),
    path('financials/cashing/file/<int:fid>', financials.CashingFileDownloadView.as_view(), name='cashing_file'),
    path('financials/cashing/signature/<int:fid>', financials.CashingSignatureFileDownloadView.as_view(), name='cashing_signature'),
    
    # Forseenbalance
    path('financials/forseenbalance/list', financials.ForseenBalanceListView.as_view(), name="fin_forseenbalances"),
    path('financials/forseenbalance/<int:balid>', financials.ForseenBalanceView.as_view(), name="fin_forseenbalance"),
    
    #Bank account operation
    path('financials/bankaccount/', financials.AccountOperationView.as_view(), name='accountoperations'),
    path('financials/bankaccount/balances', financials.AccountBalanceView.as_view(), name='accountbalance'),
    path('financials/bankaccount/<int:year>', financials.AccountOperationView.as_view(), name='accountoperations'),
    path('financials/bankaccount/processfile', financials.AccountOperationFileView.as_view(), name='accountoperations_file'),
    
    # Financial category manager
    path('financial/categories', financials.FinancialCategoryView.as_view(), name='fincat'),
    
    # Single operations
    path('financials/payment/<int:payment_id>', financials.PaymentView.as_view(), name='payment'),
    path('financials/transfer/<int:tid>', financials.TransferView.as_view(), name='transfer'),
    path('financials/operation/<int:opid>', financials.OperationView.as_view(), name='operation'),
    
    # Helloasso
    path('financials/payments/helloasso', financials.HelloassoPaymentView.as_view(), name='helloasso_payments'),
    
    # Balances
    path('financials/balance/daily', financials.BalanceView.as_view(action='balance_tmp'), name="fin_balance"),
    path('financials/balance/done', financials.BalanceView.as_view(action='balance_done'), name="fin_balance_done"),
    
    # Equipments
    path('equipment/list', equipments.EquipmentListView.as_view(), name='list_equipment'),
    path('equipment/<int:eqid>', equipments.EquipmentView.as_view(), name='equipment'),
    path('equipment/picture/<int:picture_id>', equipments.EquipmentPictureView.as_view() , name='equipment_picture'),
    path('equipment/calendar', equipments.EquipmentCalendarView.as_view(), name='calendar_equipment'),
    path('equipment/calendar/<int:year>/<int:month>', equipments.EquipmentCalendarView.as_view(), name='calendar_equipment'),
    path('equipment/group/<int:eqgrp_id>', equipments.EquipmentGroupView.as_view(), name='equipment_grp'),
    path('equipment/tracking/<int:tracking_id>', equipments.EquipmentTrackingView.as_view(), name='equipmenttracking'),
    
    # Settings
    path('settings', settings.SettingsView.as_view(), name='settings'),
    
    #Export
    path('export/season_archive/<int:sid>', settings.SeasonArchiveView.as_view(), name='season_archive'),

gucem/urls.py
# -*- coding: utf-8 -*-
#
# This file is part of GAFC.
#
# GAFC is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# GAFC is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with GAFC. If not, see <https://www.gnu.org/licenses/>. 
#
# 2022 - William Chèvremont

"""gucem URL Configuration
"""

from django.urls import include,path, re_path
from django.conf.urls import handler404, handler500, handler403
from .views import redirect_view
from django.conf import settings
from django.conf.urls.static import static

from gafc.views import handlers as gv
import gucem.settings as gset

urlpatterns = [
    path('',redirect_view),
    path('gafc/main/', include('gafc.urls'), name="intranet"),
    path('gafc/minibus/', include('vehicles.urls'), name="minibus"),
    path('gafc/formation/', include('formation.urls'), name='formation'),
    path('gafc/keys/', include('keys.urls'), name='keys'),
    re_path('gafc/[a-z]*$',redirect_view),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) # Only for development. Need static file server for production;

handler403 = gv.handler403
handler404 = gv.handler404
handler500 = gv.handler500

if gset.DEBUG:
    try:
        import debug_toolbar
        urlpatterns += [ path('__debug__/', include(debug_toolbar.urls)), ]
    except Exception as e:
        print(e)

gafc/models/gafc.py
# -*- coding: utf-8 -*-
#
# This file is part of GAFC.
#
# GAFC is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# GAFC is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with Foobar. If not, see <https://www.gnu.org/licenses/>. 
#
# 2022 - William Chèvremont


"""
Generic models
"""


from django.db import models
from .user import Person
#import gucem.settings

class Season(models.Model):
    name        = models.CharField(max_length=30, verbose_name='Saison', unique=True)
    is_default  = models.BooleanField(default=False, verbose_name='Default')
    
    def save(self, *args, **kwargs): # Ensure one defaut Season
        try:
            temp = Season.objects.get(is_default=True)
            if self.is_default and self != temp:
                temp.is_default = False
                super(Season, temp).save()
        except Season.DoesNotExist:
            self.is_default = True;
            
        super(Season, self).save(*args, **kwargs)
        
    class Meta:
        default_permissions = ('add','view','change','delete')
        
    def __str__(self):
        return str(self.name)
    
    
class StaffEmail(models.Model):
    email       = models.EmailField(unique=True)
    authorized  = models.ManyToManyField('Person')
    noauth      = models.BooleanField(default=False, verbose_name='Adresse "noreply"')
    
    class Meta:
        default_permissions = ('add', 'view', 'change', 'delete', 'send_noauth')
        
    def __str__(self):
        return self.email
    
class StaffEmailAlias(models.Model):
    email       = models.EmailField()
    main        = models.ForeignKey(StaffEmail, on_delete=models.CASCADE)
    
    
class EmailModel(models.Model):
    title       = models.CharField(max_length=250, verbose_name="Titre")
    content     = models.TextField(verbose_name="Contenu")
    
    class Meta:
        default_permissions = ('add', 'view', 'change', 'delete')
        
class FinancialCategoryTree(models.Model):
    name        = models.CharField(max_length=100, verbose_name='Nom')
    toplevel    = models.ForeignKey('FinancialCategoryTree', null=True, on_delete=models.PROTECT, verbose_name="Parent")
    
    def __str__(self):
        return self.name
    
class FinancialCategory(models.Model):
    tree        = models.ForeignKey(FinancialCategoryTree, on_delete=models.PROTECT, verbose_name="Parent")
    name        = models.CharField(max_length=100, verbose_name='Nom')
    
    def __str__(self):
        return self.name
    
    class Meta:
        default_permissions = ('add', 'change', 'delete', 'view', 'balance')        


class Category(models.Model):
    name        = models.CharField(max_length=30, verbose_name='Catégorie')
    is_global   = models.BooleanField(verbose_name='Global', default=False)
    allowed_fincat = models.ManyToManyField('FinancialCategory', related_name='allowed_categories')
    default_fincat = models.ForeignKey('FinancialCategory', null=True, on_delete=models.SET_NULL)
    
    def __str__(self):
        return self.name
    
    class Meta:
        default_permissions = ('add','change','delete', 'view', 'financial')
        
    @property
    def finids(self):
        return [ f.id for f in self.allowed_fincat.all() ]
    

class Staff(models.Model):
    person      = models.ForeignKey(Person, on_delete=models.CASCADE, verbose_name='Encadrant')
    category    = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Catégorie')
    season      = models.ForeignKey(Season, on_delete=models.CASCADE, verbose_name='Saison')
    level       = models.CharField(max_length=3,  choices=[('1CO', 'Co-encadrant'),
                                                           ('2SU', 'Encadrant'),
                                                           ('3PR', 'Professionnel')],)
    
    class Meta:
        unique_together = (('person','category','season'))
        default_permissions = ('add','change','delete')
        
    @property
    def valid_validations(self):
        r = []
        for v in self.validation_set.all():
            if v.date_end is None:
                r += [v,]
        return r
    
    def save(self, *args, **kwargs):
        if self.pk is not None and len(self.valid_validations) > 0:
            raise ValueError('Can\'t change staff subscription after validation')
        
        return super().save(*args, **kwargs)

gafc/templates/gafc/event/financial.html
{% load crispy_forms_tags %}
{% load gafc_tags %}

<div class="row">
    <div class="col-lg-6">
        {% if request.user.perms.view_payment %}
        {% if payments.count > 0 %}
        <div class="row d-none d-md-flex">
            <h6 class="col-2 col-md-2 pl-md-1 pr-md-1"> Id </h6>
            <h6 class="col-6 col-md-4"> Contrepartie </h6>
            <h6 class="col-4 col-md-2 text-nowrap"> Catégorie </h6>
            <h6 class="col-6 col-md-2 text-nowrap"> Méthode </h6>
            <h6 class="col-6 col-md-2 text-nowrap"> Montant </h6>
        </div>
        {% for p in payments %}
        <div class="row pb-1 pt-1 {% if p.refund_date %}strike alert-danger{% else %}{% cycle 'bg-light' ''%}{% endif %}">
            <div class="col-2 col-md-2 pl-md-1 pr-md-1 text-nowrap"><a href="{% url 'payment' p.id %}">#P{{ p.id }}</a></div>
            <div class="col-6 col-md-4"><a href="{% url 'person' p.person.id %}">{{ p.person.first_name|capfirst }} {{p.person.last_name|upper}}</a></div>
            <div class="col-4 col-md-2 text-nowrap"><a href="{% url 'category' p.category.id %}">{{ p.category }}</a></div>
            <div class="col-6 col-md-2 text-nowrap">{{ p.method|payMethod }}</div>
            <div class="col-6 col-md-2 text-nowrap text-right">{{ p.amount|floatformat:2 }}</div>
        </div>
        {% endfor %}
        <div class="row"><div class="col-12"><hr /></div></div>    
        {% for tt in totaux.items %}
            {% for t in tt.1.items %}
                {% if t.0 == 'cat' %}
                {% else %}
                {% ifchanged tt.1.cat.id %}<div class="row d-md-none"><div class="col-12"><hr /></div></div>{% endifchanged %}
                <div class="row">
                    <div class="col-12 col-md-6"> {% ifchanged tt.1.cat.id %}<a href="{% url 'category' tt.1.cat.id %}">{{tt.1.cat.name}}</a>{% endifchanged %} </div>
                    <div class="col-6 col-md-3 text-nowrap">{{ t.0|payMethod }}</div>
                    <div class="col-2 col-md-1 text-nowrap">{{ t.1.N }}</div>
                    <div class="col-4 col-md-2 text-nowrap text-right">{{ t.1.t|floatformat:2 }}</div>
                </div>
                {% endif %}
            {% endfor %}
        {% endfor %}  
        
        {% endif %}

        <div class="row">
            <div class="col-12 alert alert-info small">
            Allez sur la fiche du paiement (clic sur référence du paiement) pour effectuer un remboursement.
            </div>        
        </div>
        
        {% if 'add_payment' in self.forms %}
        <button class="btn btn-secondary collapsed" data-toggle="collapse" data-target="#formPaymentContent" aria-expanded="false" aria-controls="formPaymentContent"> Ajouter un paiement </button>
        
        <div class="collapse {% if form_payment.errors %}show{% endif %}" id="formPaymentContent" aria-labelledby="formPaymentHeader">
            <div class="card-body">{% crispy self.forms.add_payment %} 
            {{ form_payment.errors }}
            </div>       
        </div>
        {% endif %}
        {% if 'convert_hello' in self.forms %}
        <div class='row mt-3'><h6 class="text-center col-12">Paiements Helloasso en attente</h6></div>
        <form method="POST">
            {% csrf_token %}
            <input type="hidden" name="whattodo" value="convert_hello" />
            {% for p in hello_payments %}
            <div class='row'>
                <div class="col-8">{{ p.name }}</div>
                <div class="col-4 text-right">{{ p.amount }} &euro;</div>
                
                <div class="input-group mb-3 col-12">
        
                    <div class="input-group">
                        <input type="text" class="form-control gafc-typeahead-search rounded-left" typeahead-source="{% url 'persons_json' %}" placeholder="Adhérent" typeahead-callback="$('[name=payment][ref={{ p.id }}]').prop('checked',true)" typeahead-callback-invalid="$('[name=payment][ref={{ p.id }}]').prop('checked',false)"/>
                        <div class="input-group-append">
                            <span class="btn btn-danger pl-0 pr-0 gafc-typeahead-clean">{% b_icon 'x' 18 %}</span>
                        <div class="input-group-text">
                            <input type="checkbox" value="{{ p.id }}" ref="{{ p.id }}" name="payment" />
                        </div>
                        </div>
                    <input type="hidden" class="gafc-typeahead-value" name="hello-person-{{ p.id }}" value="{{ p.default_person.id }}"/>
                    </div>
                </div>
                <div class="input-group mb-3 col-12">
                    <select ref="{{ p.id }}" class="custom-select category_list" name="hello-category-{{ p.id }}" data-linked-account="hello-account-{{ p.id }}">
                        {% for c in g_categories %}
                        {% if c.id == e.category.id or c.is_global %}
                        <option value="{{ c.id }}" {% if c.id == e.category.id %}selected{% endif %}>{{ c.name }}</option>
                        {% endif %}
                        {% endfor %}
                    </select>
                    <select ref="{{ p.id }}" class="custom-select account_list" name="hello-account-{{ p.id }}">
                        <option value="" selected>---</option>
                        {% for v in treeval %}
                            <optgroup label="{{v.0}}">
                            {% for o in v.1 %}
                                <option value="{{ o.0 }}">{{ o.1 }}</option>
                            {% endfor %}
                            </optgroup>
                        {% endfor %}
                    </select>
                </div>
            </div>
            {% endfor %}
            <div class="row">
                <div class="offset-md-6"></div>
                <div class="col-md-6">
                    <input type="submit" value="Enregistrer" class="btn btn-primary" />
                </div>
            </div>
        </form>
        {% endif %}
        {% endif %}
    </div>

    <div class="col-lg-6">
        {% if request.user.perms.view_internalpayment %}
        {% if transfers.count > 0 %}
        <div class="row d-none d-md-flex">
            <h6 class="col-2 col-md-2"> Id </h6>
            <h6 class="col-5 col-md-3"> Débiteur </h6>
            <h6 class="col-5 col-md-3"> Créditeur </h6>
            <h6 class="col-6 col-md-2 text-nowrap"> Méthode </h6>
            <h6 class="col-6 col-md-2"> Montant </h6>
        </div>
        {% for p in transfers %}
        <div class="row d-md-none"><div class="col-12"><hr /></div></div>
        <div class="row {% cycle 'bg-light' ''%}">
            <div class="col-2 col-md-2"><a href="{% url 'transfer' p.id %}">#T{{ p.id }}</a></div>
            <div class="col-5 col-md-3"><a href="{% url 'category' p.category_d.id %}">{{ p.category_d }}</a></div>
            <div class="col-5 col-md-3"><span class="d-md-none">-> </span><a href="{% url 'category' p.category_c.id %}">{{ p.category_c }}</a></div>
            <div class="col-6 col-md-2 text-wrapword">{{ p.method|payMethod }}</div>
            <div class="col-6 col-md-2">{{ p.amount|floatformat:2 }} &euro;</div>
        </div>
        {% endfor %}
        <div class="row d-md-none"><div class="col-12"><hr /></div></div>
        {% endif %}
        
        {% if 'add_transfer' in self.forms %}
        <button class="btn btn-secondary collapsed" data-toggle="collapse" data-target="#formTransferContent" aria-expanded="false" aria-controls="formTransferContent"> Ajouter un transfert </button>

        <div class="collapse {% if self.forms.add_transfer.errors %}show{% endif %}" id="formTransferContent" aria-labelledby="formTransferHeader">
            <div class="card-body">{% crispy self.forms.add_transfer %} </div>    
        </div>
        {% endif %}
        {% endif %}
    </div>
</div> <!-- row -->

gafc/templates/gafc/event/informations.html
{% load crispy_forms_tags %}
{% load gafc_tags %}

    {% if 'save_event' in self.forms %}
    {% crispy self.forms.save_event %}
    {% else %}
    <div class="form-group row">
        <div class="col-sm-4"> Titre </div>
        <div class="col-sm-8"> {{ e.title }} </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-4"> Catégorie </div>
        <div class="col-sm-8"> {{ e.category.name }} </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-4"> Type </div>
        <div class="col-sm-8"> {{ e.eventtype|eventType }} </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-4"> Coût </div>
        <div class="col-sm-8"> {{ e.cost }} </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-4"> Description </div>
        <div class="col-sm-8"> {{ e.description|parse_markdown }} </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-4"> Lieu </div>
        <div class="col-sm-8"> {{ e.place }} </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-4"> Début </div>
        <div class="col-sm-8"> {{ e.begin|date:'d/m/Y H:i' }} </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-4"> Fin </div>
        <div class="col-sm-8"> {{ e.finish|date:'d/m/Y H:i' }} </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-4"> Saison </div>
        <div class="col-sm-8"> {{ e.season.name }} </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-4"> Lien de paiement Helloasso </div>
        <div class="col-sm-8"> <a href="{{ e.helloassoLink }}" target='_blank'>{{ e.helloassoLink }}</a> </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-4"> Visibilité </div>
        <div class="col-sm-8"> {{ e.visibility|eventVisibility }} </div>
    </div>
    <div class="row">
        <div class="col-sm-4"> Rendre publique après validation </div>
        <div class="col-sm-8"> {% if e.public_after_va %} {% b_icon 'check-square-fill' %} {% else %} {% b_icon 'square' %} {% endif %}</div>
    </div>
    <div class="row">
        <div class="col-sm-4"> Formulaire d'inscription </div>
        <div class="col-sm-8"> {% if e.link %} {% b_icon 'check-square-fill' %} {% else %} {% b_icon 'square' %} {% endif %}</div>
    </div>
    <div class="row">
        <div class="col-sm-4"> Licence valide uniquement </div>
        <div class="col-sm-8"> {% if e.onlyvalid %} {% b_icon 'check-square-fill' %} {% else %} {% b_icon 'square' %} {% endif %}</div>
    </div>
    {% endif %}
    <div class="form-group row">
        <div class="col-sm-4"> Encadrement </div>
        <div class="col-sm-8"> {{ e.duration }} jours </div>
    </div>
{% if e.link %}
    <div class="form-group row">
        <div class="col-sm-4"> Lien d'inscription </div>
        <div class="col-sm-8"> <a href="{% abs_url 'event_participation' e.id %}">{% abs_url 'event_participation' e.id %}</a> </div>
    </div>
{% endif %}

{% if 'delete_event' in self.forms %}
    {% crispy self.forms.delete_event %}
{% endif %}

{% comment %}<div class="alert alert-info small">
Cocher la case "Formulaire d'inscription" laisse la possibilité à tout utilisateur⋅trice enregistré de s'inscrire à l'événement. L'utilisateur⋅trice sera alors mis sur liste d'attente. Tant que les inscriptions sont ouvertes et que l'utilisateur⋅trice est en liste d'attente, il⋅elle a la possibilité de modifier/annuler lui⋅elle-même son inscription.</div>
<div class="alert alert-info small">
La case "Licence valide uniquement" n'autorise que les adhérents avec une licence valide à demander leur inscription. Cela ne s'applique pas à la saisie sur le formulaire ci-dessous.
</div>{% endcomment %}